- name: First interaction
  uses: actions/first-interaction@v1.1.0
- name: Auto-add contributors
  uses: BobAnkh/add-contributors@v0.0.8
- name: contributor_list
  uses: cjdenio/contributor_list@1.0
blank_issues_enabled: false
contact_links:
- name: BrainStormYourWayIn gmail ID
  url: brainstormyourwayin@gmail.com
  about: Contact us here for any query/idea.
